on:
  push:
jobs:
  test-project:
    name: Test Project
    runs-on: windows-11
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: node bubble_test
